spring:
  application:
    name: demo
  datasource:
    driver-class-name: ${processUnicodeDataSourceDriverClassName}
    url: ${processUnicodeDataSourceUrl}
    username: ${processUnicodeDataSourceUsername}
    password: ${processUnicodeDataSourcePassword}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${processUnicodeDatabasePlatform}
    properties:
      hibernate:
        "[show_sql]": ${processUnicodeDebugging}
        "[use_sql_comments]": ${processUnicodeDebugging}
        "[format_sql]": ${processUnicodeDebugging}
        "[highlight_sql]": ${processUnicodeDebugging}
        connection:
          characterEncoding: UTF-8
          charSet: UTF-8
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
